export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_USERS: 'SET_USERS',
  NOTIFICATION_BUTTON: 'NOTIFICATION_BUTTON',
  ADD_NOTIFICATION: 'ADD_NOTIFICATION',
  CLEAR_NOTIFICATIONS: 'CLEAR_NOTIFICATIONS',
  GET_NEWS: 'GET_NEWS'



};